

name: Compose Docker project

on:
  push:
    branches:
      - master

jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 
 
    - name: Build
      run: docker build -t thien-tm:v1 
    - name: Run
      run: docker run -d -p 3052:80 thien-tm:v1
