

name: Compose Docker project

on:
  push:
    branches:
      - master

jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 
    - name: Clear
      run: docker stop thien-tm || true && docker rm thien-tm || true
    - name: Build
      run: docker build -t thien-tm:v1 .
    - name: Run
      run: docker run -d -p 3052:80 --name thien-tm thien-tm:v1
